version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: webadmin
      POSTGRES_USER: webadmin
      POSTGRES_PASSWORD: webadmin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      AUTH_SECRET: "local-secret"
    ports:
      - "8001:8000"

  webadmin:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DJANGO_SECRET_KEY: "local-django"
      DJANGO_DEBUG: "true"
      POSTGRES_DB: "webadmin"
      POSTGRES_USER: "webadmin"
      POSTGRES_PASSWORD: "webadmin"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      AUTH_SERVICE_URL: "http://auth:8000"
    depends_on: [db, auth]
    ports:
      - "33333:8000"

volumes:
  pgdata:
