apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: webadmin
spec:
  type: NodePort
  selector: { app: auth }
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.auth.nodePort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: webadmin
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth }
  template:
    metadata:
      labels: { app: auth }
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
        - name: auth
          image: {{ .Values.auth.image | quote }}
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.env.AUTH_SECRET_SECRET }}
                  key: {{ .Values.auth.env.AUTH_SECRET_KEY }}
          ports:
            - containerPort: 8000
